### ISSUE TITLE
Front-end to-do check list

### ISSUE THREAD

**Issue by GISRedeDev** [OxfordDemSci/UkraineNowPop#23]
- [x] Add functionality to select Sex 
- [ ] Reflect selected Sex to demographic structure of population pyramid ( based on selected sex)
- [x] Add authentication/sign in option and capturing timing out of time limit
- [x] Add functionality of selection Geo
- [x] Load shapefile based on selected Geo
- [ ] Add custom colour/palette configuration
- [x] Add settings menu for a user to choose  a) limit of migration data to return b) showing labels of the map
- [x] Question modal popups for all boxes
- [ ] Add names of admin units in migration flow chart 
- [x] Add reset option allowing user to get to default 
- [x] test memory usage of dashboard JavaScript scripts in browser (slow performance)

**Comment by doug-leasure** [comment]
@GISRedeDev , maybe we can close this issue and transfer any remaining items over to issue #37

**Comment by GISRedeDev** [comment]
Yeah, I'm good to close it (this is David). I didn't add to this checklist. Do you know whether these items are still required?
